server:
  port: 7002

spring:
  application:
    name: recommendation
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/recommendations-db}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
